name: CI (Wallet)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        working-directory: wallet-extension
        run: npm ci || npm i
      - name: Build
        working-directory: wallet-extension
        run: npm run build || npm run dev -- --outDir dist
      - name: Package
        run: |
          cd wallet-extension
          zip -r ../mothership-wallet-dist.zip dist manifest.json public src -x '**/node_modules/**'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mothership-wallet-dist
          path: mothership-wallet-dist.zip
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
